### ISSUE TITLE
ERROR: missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by daniel712** [chestm007/amdgpu-fan#30]
unfortunately not running here an debian bullseye and AMD Navi (5700 XT):

Traceback (most recent call last):
  File "/usr/local/bin/amdgpu-fan", line 8, in <module>   sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/amdgpu_fan/controller.py", line 76, in main   config = ad_config(CONFIG_LOCATIONS[-1])
  File "/usr/local/lib/python3.9/dist-packages/amdgpu_fan/controller.py", line 44, in load_config   return yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by 19721dan** [comment]
same problem. always worked before. mxlinux 21

**Comment by codesnippy** [comment]
Same issue here Also Debian Bullseye

**Comment by jacness12334** [comment]
Same issue, debian bullseye.

**Comment by sanwill** [comment]
The amdgpu-fan package at  pip is not updated with this fix.
The error was resolved after apply the fix, tested on Fedora and Ubuntu.

**Comment by chestm007** [comment]
pip package needs to be updated
