### ISSUE TITLE
KeyError: 'pwm1_min'

### ISSUE THREAD

**Issue by YuruiHong** [chestm007/amdgpu-fan#33]
Installed the lasted version from GitHub, but got this:

```python
starting amdgpu-fan
Traceback (most recent call last):
  File "/usr/local/bin/amdgpu-fan", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/amdgpu_fan/controller.py", line 78, in main
    FanController(config).main()
  File "/usr/local/lib/python3.11/dist-packages/amdgpu_fan/controller.py", line 35, in main
    logger.debug(f'{name}: Temp {temp}, Setting fan speed to: {speed}, fan speed{card.fan_speed}, min:{card.fan_min}, max:{card.fan_max}')
                                                                                                       ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/amdgpu_fan/lib/amdgpu.py", line 64, in fan_min
    return int(self.read_endpoint('pwm1_min'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/amdgpu_fan/lib/amdgpu.py", line 36, in read_endpoint
    with open(self._endpoints[endpoint], 'r') as e:
              ~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'pwm1_min'
```

Also tried all the pull request versions and got the same error.🌚

**Comment by visionscaper** [comment]
I also have the exact same error. @chestm007 Any idea what could be the problem here? Thanks.

**Comment by RGD2** [comment]
I believe this is because the code assumes all cards support that item in the `/sys/class/drm/card0/device/hwmon/hwmon2/` directory. I get this crash because I've got built-in graphics showing up in `/sys/class/drm/card1/device/hwmon/hwmon3/`, and  there's no `pwm1_min` endpoint in that directory, hence the `KeyError`.

Code needs a change to fail gracefully in such cases - preferably to ignore cards which don't have the right endpoints.
Workaround might be to disable the on-CPU graphics so it doesn't show up to confuse amdgpu-fan.

**Comment by RGD2** [comment]
Better workaround:
append this to your `/etc/amdgpu-fan.yml` file:
```
cards:
- card0
```

This is enough to make it ignore card1, the built-in graphics. Solved the issue for me immediately.

**Comment by chestm007** [comment]
@YuruiHong @RGD2 @visionscaper @gokaybiz 
Could you guys please test the changes in the PR and let me know if it fixes the problem?

**Comment by ahmaddie1378** [comment]
still same bug , i using yay version

**Comment by chestm007** [comment]
Can you try the lastest version in this repo and post any logs, errors that are produced?.

 If you can list the filesystems under

/sys/class/drm/card*/device/hwmon/hwmon*/

That might help me understand the file structure and where this program is failing.
You might need to change '*' to numbers and such

Any logs or exceptions would be helpful too!

**Comment by uberstar100** [comment]
> Can you try the lastest version in this repo and post any logs, errors that are produced?.
> 
> If you can list the filesystems under
> 
> /sys/class/drm/card*/device/hwmon/hwmon*/
> 
> That might help me understand the file structure and where this program is failing. You might need to change '*' to numbers and such
> 
> Any logs or exceptions would be helpful too!

I tried this as I currently had the same issue. With the latest PR, this is the result:

```
skipping card: card0 as its missing endpoint pwm1_max
no compatible cards found, exiting
```
This is with and without the additional workaround proposed here: https://github.com/chestm007/amdgpu-fan/issues/33#issuecomment-2180752124

And this is where my GPU system files are stored in (take note of the bus numbers outputted from `lspci`, I have a dedicated GPU and an integrated one respectively):

```
$ lspci | grep VGA
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)
10:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raphael (rev c7)
```


<details>
<summary>ls -la /sys/class/drm/card1/device/hwmon/hwmon3/ (where my dedicated GPU lives)</summary>

```
$ ls -la /sys/class/drm/card1/device/hwmon/hwmon3/ | awk '{print $9, $10, $11}' 
.  
..  
device -> ../../../0000:03:00.0
fan1_enable  
fan1_input  
fan1_max  
fan1_min  
fan1_target  
freq1_input  
freq1_label  
freq2_input  
freq2_label  
in0_input  
in0_label  
name  
power  
power1_average  
power1_cap  
power1_cap_default  
power1_cap_max  
power1_cap_min  
power1_label  
pwm1  
pwm1_enable  
pwm1_max  
pwm1_min  
subsystem -> ../../../../../../../../class/hwmon
temp1_crit  
temp1_crit_hyst  
temp1_emergency  
temp1_input  
temp1_label  
temp2_crit  
temp2_crit_hyst  
temp2_emergency  
temp2_input  
temp2_label  
temp3_crit  
temp3_crit_hyst  
temp3_emergency  
temp3_input  
temp3_label  
uevent  
```

</details>


<details>
<summary>ls -la /sys/class/drm/card0/device/hwmon/hwmon4/ (where my integrated GPU lives) </summary>

```
$ ls -la /sys/class/drm/card1/device/hwmon/hwmon3/ | awk '{print $9, $10, $11}' 
.  
..  
device -> ../../../0000:10:00.0
freq1_input  
freq1_label  
in0_input  
in0_label  
in1_input  
in1_label  
name  
power  
power1_input  
power1_label  
subsystem -> ../../../../../../class/hwmon
temp1_input  
temp1_label  
uevent
```

</details>

As I finish writing this, I realized it started working without the changes from the PR, but with the aforementioned workaround proposed lol.. Hope this was helpful anyway..

**Comment by chestm007** [comment]
The changes from the PR didnt ever return that the card passed verification, my bad. Latest master commit should have this fixed though. If you could try it and let me know it would be greatly appreciated 😄
